@startuml
'https://plantuml.com/deployment-diagram

partition preprocessing {
(*) -left-> crop images to square format
if "" then
    --> [train] train model on "train" and "val" data
    --> evaluate model on "test" data
else
    --> [load] load model from folder
    --> evaluate model on "test" data
-right-> calculate feature embeddings\nfor all "train" and "val" data\nbased on the model
-right-> [A] generate LRP heatmaps\nfor all "train" and "val" data\nbased on the model
-up-> [A] select prototypes
}
partition nhnm {
-up-> generate near hits and near misses
-up-> evaluate near hits and near misses
-left-> (*)
}

@enduml
